export const IMAGES = {
  logo: "/images/logo.png",
  logo2: "/images/logo2.png",
  carousel1: "/images/carousel1.jpg",
  gray: "/images/gray.png",
  aoPhao1: "/images/aophao1.webp",
  aoPhao2: "/images/aophao2.jpg",
  aoPhao3: "/images/aophao3.webp",
  aoPhao4: "/images/aophao4.avif",
  aboutus: "/images/aboutus.webp",
  banner1: "/images/banner1.webp",
  banner2: "/images/banner2.webp",
  banner3: "/images/banner3.webp",
  hoboi1: "/images/hoboi1.webp",
  hoboi2: "/images/hoboi2.webp",
  hoboi3: "/images/hoboi3.webp",
  nhapho1: "/images/nhapho1.webp",
  nhapho2: "/images/nhapho2.webp",
  mayloc: "/images/mayloc.jpg",
  denled: "/images/denled.jpg",
  voiphun: "/images/voiphun.jpg",
  gach: "/images/gach.jpg",
  maybom: "/images/maybom.jpg",
  cauThang: "/images/cauThang.jpg",
  taosong: "/images/taosong.jpg",
  hoachat: "/images/hoachat.jpg",
};
